### ISSUE TITLE
provide more authors the ability to merge

### ISSUE THREAD

**Issue by ohadlevy** [abenari/rbovirt#101]
Hi @abenari 

would you mind allowing others (such as @lzap and @inecas) the ability to merge to the repository? 

thanks!

**Comment by lzap** [comment]
As well as @ares thanks!

**Comment by abenari** [comment]
Added, happy coding everyone.

**Comment by lzap** [comment]
Thanks, one additional request if you could do:

```
gem owner -a lzap@seznam.cz
gem owner -a necasik@gmail.com
```

Thanks!
