### ISSUE TITLE
VM's maximum_memory_size in oVirt 4.1

### ISSUE THREAD

**Issue by milanzelenka** [abenari/rbovirt#118]
oVirt 4.1 brings Maximum memory size VM parameter:

http://www.ovirt.org/develop/release-management/features/engine/maximum-memory-size/

In Foreman when I tried to create VM with > 4GB RAM (which is default value of maximum-memory-size).

 I get: "Cannot add VM. Memory size (65536MB) cannot exceed maximum memory size (4096MB)."

Is this problem of rbovirt?

**Comment by lzap** [comment]
Ahoj Milane,

this does not appear to be bug in rbovirt, rather than oVirt. Please use mailing list to get support.
