### ISSUE TITLE
Status field should be handled generically in base object

### ISSUE THREAD

**Issue by abonas** [abenari/rbovirt#50]
Based on discussion in pull request #44 

Status field is part of base_object in oVirt, and is treated in several different entities in rbovirt making it a "copy paste".
So, it's better to handle it once in base_object in rbovirt, and it will just remain unpopulated for entities that currently don't populate it in oVirt. most of the entities in rbovirt do handle it.
While doing that, the status field should be handled correctly by parsing "status/state" and not just "status" as done in some entities.

**Comment by abenari** [comment]
@abonas interested in fixing that? or should I close.

**Comment by abonas** [comment]
@abenari sorry I just got a notification on that. I am not actively working on this. But I don't see any reason why to close this issue, anyone can pick and fix it, it's good to have it as a reference that it needs fixing.

**Comment by abenari** [comment]
@abonas, I tend to keep issues for functional and compatibility problems as I want issues to reflect the status of the library, re-factoring patches are most welcome.
