### ISSUE TITLE
Fix Overriden Rest Client delete method compatibility issues in other projects

### ISSUE THREAD

**Issue by pdilung** [abenari/rbovirt#63]
As reported by @ehelms in pull request #62, overriding default `RestClient::Resource#delete` method introduced compatibility issues and breaks any other projects that uses rbovirt.

@ehelms has provided a fix for this in #62 :+1:  I have tested the proposed change and it works fine.

I propose to roll back the `OVIRT::Client#http_delete` to its version from d0e6726431aaced3cdab711178f123117e34eed7 and implement `OVIRT::Client#http_delete_with_payload`.

I shall created a pull request that will include @ehelms' #62 and the proposal above.

**Comment by pdilung** [comment]
@abenari would you be interested in pull request #64 or I can disregard it and implement #65 on top of master (8961745215240a80e7caec273d7324d00853f036)?

**Comment by abenari** [comment]
@pdilung you can rebase this pull request and push it to this branch, if you think it's needed else you can close it. I thought @ehelms patch fixed the issue.

**Comment by pdilung** [comment]
@abenari the patch made by @ehelms fixes the issue. So if you do not see any reason to have  separated DELETE methods, one with the other without payload in `OVIRT::Client`, then #63 and #64 can be closed. Thanks.

**Comment by abenari** [comment]
Closed as aggreed
