### ISSUE TITLE
Implement affinity groups

### ISSUE THREAD

**Issue by pdilung** [abenari/rbovirt#67]
I am about to implement affinity groups thus opening a ticket to keep track of the progress.

Details about affinity groups can be found in [RHEV Administration Guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.4/html/Administration_Guide/sect-Affinity_Groups.html) as well as in [RHEV Technical Guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.4/html/Technical_Guide/sect-Affinity_Groups_Sub-Collection.html)

**Comment by pdilung** [comment]
I have done an initial implementation of [affinity groups](https://github.com/pdilung/rbovirt/compare/affinity_groups) feature.
I have tested this in RHEV 3.4 and seems to work ok.
Following are the features of this implementation
* List affinity groups
* List a given affinity group
* List VMs assigned to this affinity group
* Create new affinity group
* Destroy an affinity froup
* Assign a VM to an affinity group
* Remove a VM from an affinity group

@abenari I have created a separate `affinity_group_api.rb`, however according to RHEV [Technical Guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.4/html-single/Technical_Guide/index.html#sect-Affinity_Groups_Sub-Collection) it is a sub collection of [Clusters collection](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.4/html/Technical_Guide/chap-Clusters.html). Please let me know if you want me to move `affinity_group_api.rb` into `cluster_api.rb`.

**Comment by pdilung** [comment]
@abenari Any updates here? Thanks.

**Comment by abenari** [comment]
@pdilung a separate file for the affinity group sounds good, once you'll send the pull request I'll be happy to review the code.
Thanks,
 Amos.

**Comment by pdilung** [comment]
@abenari, PR is ready #69.
