### ISSUE TITLE
Disk is not activated after adding it

### ISSUE THREAD

**Issue by smags** [abenari/rbovirt#78]
Testing Foreman 1.7.4 and OVirt 3.5 i found that after adding a disk via Foreman the disk is created, added to the VM but not activated.

It seem an "activate" function is missing from rbovirt or the default behaviour after adding a disk was changed in the OVirt 3.5 api. Where disks activated before OVirt 3.5?

**Comment by pdilung** [comment]
Hi, I am working with RHEV 3.4 and disks are activated when added.

**Comment by smags** [comment]
There is an open ticket for RHEV 3.4.1: http://projects.theforeman.org/issues/7649
And seems only to happen if the VM is running while adding the disks.

**Comment by smags** [comment]
So i tested a bit more...

If you use:
curl -X POST -H "Accept: application/xml" -H "Content-Type: application/xml" -u admin@internal:password -k -d "<disk><storage_domains><storage_domain id='028e4fb6-679a-463a-9a00-66125c5b1cd9'/></storage_domains><size>10485760</size><type>system</type><interface>virtio</interface><format>cow</format><bootable>false</bootable></disk>" https://localhost/api/vms/fd1f4b31-2fcb-429d-be45-844fdcc05be7/disks

the disk is not activated, adding <active>true</active> does the trick.

curl -X POST -H "Accept: application/xml" -H "Content-Type: application/xml" -u admin@internal:password -k -d "<disk><storage_domains><storage_domain id='028e4fb6-679a-463a-9a00-66125c5b1cd9'/></storage_domains><size>10485760</size><type>system</type><interface>virtio</interface><format>cow</format><active>true</active><bootable>false</bootable></disk>" https://localhost/api/vms/fd1f4b31-2fcb-429d-be45-844fdcc05be7/disks

Now the disk is activated.

**Comment by smags** [comment]
Would it be ok if i add an "active" option to volume.rb (like the wipe_after_delete option)?

**Comment by pdilung** [comment]
@smags Would make sense. Are you able to add this into rbovirt?

**Comment by pdilung** [comment]
@smags  There is a support for volume [activation](https://github.com/abenari/rbovirt/blob/master/lib/client/vm_api.rb#L101) and [deactivation](https://github.com/abenari/rbovirt/blob/master/lib/client/vm_api.rb#L105) (see #61). I have added this functionality to be able attach and detach floating disks. 

I am not using Foreman, but perhaps it would make sense to ask some of Foreman people (@ohadlevy et al) whether activation/deactivation could be implemented into Foreman.

**Comment by smags** [comment]
@pdilung At first i thought so too. But if i read the unit tests correctly '''active=true''' is used there. Also it would be just one call to RHEV/Ovirt. Is the option '''active=true''' as default working against OVirt < 3.4.1 or would that create a problem?

**Comment by smags** [comment]
@pdilung Just found out that ```attach_volume```already has an activate in it. So it should work. Will try to  test it in the next days.

**Comment by smags** [comment]
@pdilung Ok, i'm hanging my head in shame. Foreman uses Fog to interface with OVirt and they don't have an option for activate after attaching the disk. I was misled because rbovirt was installed as a requirement with Foreman.

The foreman team has to implement a 2nd call to Fog tho. Sorry for taking up your time!

**Comment by pdilung** [comment]
@smags Fog counterparts of activate and deactivate exist in fog.
