### ISSUE TITLE
new branch to be compatible with older rest-client versions

### ISSUE THREAD

**Issue by karmab** [abenari/rbovirt#82]
hello, 
we d like to have a branch created to support rest-client <= 1.7.3
and backport some features from current 0.1.0 release

**Comment by pdilung** [comment]
@abenari, @jhernand: Would it be possible to help @karmab ?

**Comment by jhernand** [comment]
I have just created a new `stable-0.0` branch, starting in the commit of the latest `0.0.x` release, to be precise the `0.0.35` release. Please backport the relevant changes to that branch and we will do a `0.0.36` release when they are complete.
