### ISSUE TITLE
Error while deleting VM from Foreman

### ISSUE THREAD

**Issue by JvdW** [abenari/rbovirt#98]
I'm on oVirt-3.6.1/foreman-1.10 and that is using rbovirt-0.0.35 and when I try to delete a VM I get an error in the log of foreman.
```
2016-01-03 10:43:13 [app] [W] Action failed
 | NoMethodError: undefined method `text' for nil:NilClass
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rbovirt-0.0.35/lib/ovirt/vm.rb:240:in `parse_xml_attributes!'
```
Line 240 is:
`:type => (xml/'display/type').first.text,`

That triggered a memory that there was a change from oVirt-3.5.Z to oVirt-3.6.Z in the handling of the console display. There is now an entry 'Video Type' which is either Cirrus or QXL. Looks like its not set for VMs that has been around from before the upgrade to 3.6. Saving the VM configuration fixes the rbovirt error but being defensive about what line 240 returns would save me and others, a lot of edit VM/save VM actions.

Joop

**Comment by JvdW** [comment]
Adding a rescue nil to line 240 didn't work, adding it to line 245 did the trick. I can delete 'old' oVirt-3.5 created VMs.

**Comment by mmoll** [comment]
similar to #97 maybe?

**Comment by JvdW** [comment]
On February 7, 2016 3:44:04 AM CET, Michael Moll <notifications@github.com> wrote:
>similar to #97 maybe?
Yeah. Looks like it includes what I did to get things running again. 

Joop
-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by lzap** [comment]
Fixed with https://github.com/abenari/rbovirt/pull/105 - we will be releasing new gem soon.
